### PR TITLE
[Newsletter: August] XMPPIoT coffee maker

### PR DESCRIPTION
**Pull request by COM8**
First draft for the XMPPIoT enabled JURA coffee maker.

### CODE REVIEW

**Comment by Echolon** [comment]
@COM8 thanks for the contribution! That is really good news!

One thing: Can you remove the picture with just a text place holder as a reminder for me? I will add the pictures myself later. can you send it to me privately?

**Review by Echolon — COMMENTED** [review]
- Please replace the picture with a simple reminder text for me

**Comment by Echolon** [comment]
@COM8 sorry - I meant a text placeholder - no pictures in general. I have to do that myself later.

**Comment by COM8** [comment]
Ah, right :D
Fixed it and you should have a mail with the actual image in your inbox.

**Comment by Echolon** [comment]
Thanks a lot for your patients and the changes!

Enjoy your XMPP coffee! :coffee:

**Pull request merged**
