### PR TITLE
Libraries: add DOAP file for slixmpp

### PR DESCRIPTION
**Pull request by mathieui**
(and renew as a side effect)

### CODE REVIEW

**Review by Echolon — APPROVED** [review]
Thanks!

**Review by Echolon — COMMENTED** [review]
Ehm, -> the link does not work?

**Comment by mathieui** [comment]
@Echolon sadly the whole gitlab instance is down at the moment, but otherwise this is the correct URI!

**Review by Echolon — APPROVED** [review]
Alright, thanks!

**Pull request merged**
