### PR TITLE
Change Dropdown menu element order and add Roadmap

### LINKED ISSUE #564: Link to XSF Roadmap from "About the XSF" sidebar
Hi! Have you considered linking to the XSF Roadmap from the "About the XSF" sidebar like in the screenshot below?

Screen Shot 2019-05-11 at 9 08 45 PM

I'm talking about the page at https://xmpp.org/about/xsf/roadmap

Thanks.

### PR DESCRIPTION
**Pull request by Echolon**
Closes #564

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
Changing the dropdown menu order is possible via `/config/_default/menus.en.toml`.

**Comment by Echolon** [comment]
@wurstsalat3000 I don't understand the logic really how what link is shown when and how the choice of which links are shown works :/

**Comment by wurstsalat3000** [comment]
Each parent item offers an "identitier", by which children can be assigned to via a "parent" link. Menu items are ordered by "weight".

**Comment by wurstsalat3000** [comment]
@Echolon I changed the menu order in 27cb662e70712575d103bfb6724af445d522120a

Would you be ok with closing this PR until the 'Roadmap' page has been updated?

**Comment by Echolon** [comment]
@wurstsalat3000 thanks, yes let's close it. Still I'm a bit of confused here

**Pull request closed without merging**
