### PR TITLE
Add Mailfence to Site: Use of XMPP

### PR DESCRIPTION
**Pull request by Mailfence-team**

### CODE REVIEW

**Review by Echolon — APPROVED** [review]
Thanks, great choice ;-)

**Comment by Echolon** [comment]
Please do not merge currently!

**Comment by Echolon** [comment]
Hi @Mailfence-team ,

we have been upgrading from Pelican to the Hugo website generator. Could you review this in case it is still relevant?

That would be really great!

**Comment by wurstsalat3000** [comment]
The page's path changed a bit. It's now located at `content/uses/instant-messaging.md`.

**Comment by Mailfence-team** [comment]
Hi @Echolon, @wurstsalat3000,

I've opened #968 instead.

**Pull request closed without merging**
