### PR TITLE
[newsletter] Review

### PR DESCRIPTION
**Pull request by wurstsalat3000**

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
@Echolon

**Comment by Echolon** [comment]
Thanks! However, there is an build error. Can you review? Maybe there is a space between the links?

**Comment by Echolon** [comment]
Can you review that you really reviewed the last version of the newsletter?

**Review by Echolon — CHANGES_REQUESTED** [review]
Ahh, sorry. You did review the latest. My bad!

**Comment by wurstsalat3000** [comment]
So, is there something to do or not?

**Review by Echolon — APPROVED** [review]
Content is fine. Just wondering why it does not build

**Pull request merged**
