### PR TITLE
Fiscal host blog

### PR DESCRIPTION
**Pull request by SamWhited**
This is a quick blog post announcing the newly passed fiscal hosting.

Blocking on #915, please merge that first.

### CODE REVIEW

**Review by Echolon — COMMENTED** [review]
I would write simply

a fiscal host

without any quotation.

It might be helpful for projects to list step by steo the process and how it circles.

**Comment by Echolon** [comment]
In general let's get it reviewed and merged before the 30th Sept!

**Comment by SamWhited** [comment]
Fixed; thanks. That did seem weird.

**Comment by SamWhited** [comment]
Added a few screenshots of the process as well as a link to the Open Collective Fiscal Hosts FAQ (which I probably should have linked on the terms of service page too; maybe later).

**Review by wurstsalat3000 — APPROVED** [review]

**Review by Echolon — APPROVED** [review]

**Pull request merged**
