### PR TITLE
Add fiscal host policy

### PR DESCRIPTION
**Pull request by SamWhited**
Add an initial draft of the policy for fiscal hosting.

### CODE REVIEW

**Comment by SamWhited** [comment]
What does me being an assignee mean? Is there something I need to do here?

**Comment by Echolon** [comment]
No, I actually means nothing. I just try to keep things a bit organised

**Comment by Echolon** [comment]
But the money will be donated directly to the proct, not via the XSF?

**Comment by SamWhited** [comment]
Sort of. The money is donated to the XSF and earmarked for that particular project. This is called "fiscal sponsorship". Eg. if you don't have the resources to do accounting and create an organization to own your project you can let the XSF take money on your behalf and distribute it to you, this way your donors can take advantage of the XSF's non-profit status and get a tax break and you don't have to figure out how to keep track of donations.

**Comment by Echolon** [comment]
Ah, ok yes is good. I was just wondering if we want to set any limits on that or whether we have to? (Well, it would be nice if people start to donate lot of course!)

**Review by mwild1 — CHANGES_REQUESTED** [review]
Assuming approval by the board, this PR will need some small tweaks now that we are using Hugo. Only to the metadata should be affected, and probably only removing some of the redundant entries is all that's needed. Other pages in the same section should serve as an example of what's needed.

It's okay to postpone any changes until after definite approval of the policy.

**Comment by SamWhited** [comment]
Updated for Hugo. I also took the liberty of adding a menu item under the community menu.

**Review by wurstsalat3000 — APPROVED** [review]

**Comment by SamWhited** [comment]
Maybe this should all be under "about" instead?

**Review by mwild1 — APPROVED** [review]

**Comment by mwild1** [comment]
Merged as-is. We can still move it if desired. I personally did look for it under "About" first, but I have no strong feelings. It is a service for the community, so that makes equal sense to me.

**Comment by SamWhited** [comment]
Thank you! I am enabling applications in Open Collective now and adding the link to this page!

**Review by Echolon — COMMENTED** [review]
@SamWhited can you make the HTTP links as a reference behind the words?

**Pull request merged**
