### PR TITLE
clients: Add new platforms to Kaidan

### PR DESCRIPTION
**Pull request by LNJ2**
Kaidan now also supports iOS, macOS, Ubuntu Touch and Windows. There haven't been
released official builds yet though (they will come with the next release).

### CODE REVIEW

**Comment by LNJ2** [comment]
I added Ubuntu Touch as platform, because I don't think it's still "normal" Linux (Desktop). Also it has its own packaging format and [store](https://open-store.io/).

**Comment by LNJ2** [comment]
If you're unsure about Ubuntu Touch, I can also remove it for now.

**Comment by guusdk** [comment]
Ah, I forgot about this one, sorry for the delay.

Indeed - we generally don't add more platforms that we already have. The rationale behind that is that otherwise, we'd have an ever-growing list of platforms, of which most are pretty obscure. People that are using such a niche platform are likely competent enough in finding software that fits their platform.

Maybe you want to add 'other' ?

**Comment by LNJ2** [comment]
Other seems to be a good idea :)

**Comment by LNJ2** [comment]
Updated

**Comment by guusdk** [comment]
Thank you!

**Pull request merged**
