### PR TITLE
Renew listing MongooseIM

### PR DESCRIPTION
**Pull request by erszcz**

### CODE REVIEW

**Comment by Echolon** [comment]
@erszcz thanks for updating!

CC:
@SeveFP

**Comment by erszcz** [comment]
Is there a plan to redeploy xmpp.org in the foreseeable future? I'd love to see this change on https://xmpp.org/software/servers.html :)

Normally, I'd just wait for the newsletter (I guess this also requires a redeployment), but I'm aware that there's not going to be a December edition, so we'd have to wait until January 2021.

**Comment by Echolon** [comment]
@erszcz may you reach out to the iTeam muc if you don't get an answer here?

iteam@muc.xmpp.org

**Comment by SeveFP** [comment]
@erszcz The changes are now live :)

**Comment by erszcz** [comment]
That's fantastic, thank you!

**Pull request merged**
