### PR TITLE
Renew QXmpp

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew QXmpp

### CODE REVIEW

**Comment by Echolon** [comment]
@melvo

**Comment by Neustradamus** [comment]
Dear @lnjX, @melvo: There is a problem to renew QXmpp. Please comment here.

**Comment by Echolon** [comment]
Got confirmation from developer

**Comment by Neustradamus** [comment]
Thanks @lnjX, @melvo, I am always happy to help XMPP projects like yours ;)

**Comment by melvo** [comment]
You are welcome. Thanks for the update.

**Pull request merged**
