### PR TITLE
Remove discontinued Google Talk from Overview page

### PR DESCRIPTION
**Pull request by butyoutried**

### CODE REVIEW

**Comment by Echolon** [comment]
Hi,

many thanks for the clean-up.

Would it be okay to rather make a historic section below? maybe with some years range?

25 may 2024 12:35:03 butyoutried ***@***.***>:

**Comment by Neustradamus** [comment]
I think it is better to have "such as Google Talk" without a link.

**Comment by Echolon** [comment]
> I think it is better to have "such as Google Talk" without a link.

Can we rather use: https://en.wikipedia.org/wiki/Google_Talk

**Comment by Neustradamus** [comment]
@cal0pteryx: Can you add Google Talk in the cited page?
- https://xmpp.org/uses/instant-messaging/

Note: For me jitsi has stopped the XMPP service a long time ago and there was not the specified number.

**Comment by butyoutried** [comment]
> Hi, many thanks for the clean-up. Would it be okay to rather make a historic section below? maybe with some years range?

Hi, @Echolon. I'm sorry for missing your message :(

**Pull request merged**
