### PR TITLE
Renew Libervia

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew Libervia

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
@goffi-contrib ?

**Comment by goffi-contrib** [comment]
Oh yes I've again missed the renewal date. It should be done indeed, so thanks @Neustradamus for this PR.

@wurstsalat3000 it's fine by me, you can merge it, thanks!

**Comment by Echolon** [comment]
@goffi-contrib also a suggestion for you to place a DOAP file. We will soon better promote clients in the new website setup.

**Comment by goffi-contrib** [comment]
@Echolon yes I know, it's planed, I'm just overwhelmed. Will do at some point.

**Pull request merged**
