### PR TITLE
Renew Miranda NG

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew Miranda NG

### CODE REVIEW

**Comment by Echolon** [comment]
@Neustradamus its nice of you providing the PRs but at least you will need to get the cobfirnation fron the developers first. So better rrefuse from creating more PRs

**Comment by Echolon** [comment]
@Neustradamus can you try to find developers from this project?

**Comment by Neustradamus** [comment]
@Echolon: It is here: https://github.com/miranda-ng.

Dear @georgehazan, there is a problem here.

**Comment by georgehazan** [comment]
@Echolon hi, I am the owner of this project.
Miranda NG is very well alive, so you can prolong its existence as XMPP client with an easy heart 😏
Feel free to ask me any questions about Miranda.
WMBR, George Hazan.

**Pull request merged**
