### PR TITLE
add stravaganza lib to libraries.json

### PR DESCRIPTION
**Pull request by ortuman**

### CODE REVIEW

**Comment by guusdk** [comment]
Hi, thanks for your contribution!

The repository that contains this project seems to have next to no activity: it has exactly one commit, one contributor, one commit. This looks strange to me. Can you tell us more about this project?

**Comment by ortuman** [comment]
👋 Hi Guus! 

This library actually forms part of a broader project called [jackal](https://github.com/ortuman/jackal) which is basically an XMPP Go server implementation.

My idea was to extract this component from the overall project so that others can benefit from it.

**Comment by Ppjet6** [comment]
Hi @ortuman, can you rebase the branch? :)

**Comment by ortuman** [comment]
👌 Done!

**Comment by Ppjet6** [comment]
Thanks!

**Pull request merged**
