### PR TITLE
please add monocles chat

### PR DESCRIPTION
**Pull request by 12aw**
added monocles chat

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
@12aw are you affiliated to "monocles chat" ?

**Comment by 12aw** [comment]
I'm the main dev. Monocles chat is a free open source client on f-droid and compatible with other xmpp servers.

**Comment by wurstsalat3000** [comment]
Alright! I'd like to encourage you to provide a DOAP file for monocles chat. This would allow us to render more infos about your client, like shown here: https://github.com/xsf/xmpp.org/pull/986

An example DOAP file can be found here: https://github.com/iNPUTmice/Conversations/blob/master/conversations.doap

**Comment by 12aw** [comment]
Thanks, done :)

**Comment by Echolon** [comment]
Was there a PR for the doap file?

**Comment by 12aw** [comment]
should be, is it gone?

**Comment by 12aw** [comment]
I've send the merge request to @wurstsalat3000

**Comment by wurstsalat3000** [comment]
@12aw that's not how it works. You'll have to PR this repository here, like you did to add the monocles chat entry.

**Pull request merged**
