### PR TITLE
Add Telepathy, update Kopete

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by Echolon** [comment]
@bkmgit Hi,

many thanks for the PR. I have to ask this: Are you officially involved in the projects?

**Comment by bkmgit** [comment]
Not at present. Update from a user.

**Comment by Echolon** [comment]
> Not at present. Update from a user.

Ok, that is alright. But could you ask an official of these projects to confirm your PR?

We have a rule that only developers / maintainer should update this.

**Comment by wurstsalat3000** [comment]
A maintainer would need to update this entry in order to state that the project(s) are still maintained.

**Pull request closed without merging**
