### PR TITLE
Software: Update DOAP, URL, and Platforms for jabber.el

### PR DESCRIPTION
**Pull request by josephmturner**
Thank you!!

### CODE REVIEW

**Comment by cal0pteryx** [comment]
Thanks! Platforms and URL are not necessary, since the DOAP file already provides those.

**Comment by cal0pteryx** [comment]
Make sure to add all platforms, like `<os>Linux</os>`. It seems the platforms you wanted to add are not contained in your DOAP file yet.

**Comment by josephmturner** [comment]
> Make sure to add all platforms, like `<os>Linux</os>`. It seems the platforms you wanted to add are not contained in your DOAP file yet.

Thanks [we're on it](https://codeberg.org/emacs-jabber/emacs-jabber/pulls/57).

**Comment by josephmturner** [comment]
@cal0pteryx It appears that `jabber.el` now shows up on the [main software page](https://xmpp.org/software/), but the [page for jabber.el](https://xmpp.org/software/jabber-el/) doesn't show the correct compliance info.  Is there an issue with the DOAP file?

**Comment by cal0pteryx** [comment]
@josephmturner two things come into play here:

* the rdf namespace should be `xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"` (note it's http, not https)
* running [compliancer](https://code.zash.se/compliancer/file/tip) ([download](https://prosody.im/files/compliance)) on the DOAP file reveals that several XEPs are missing for compliance.  Compliancer only recognizes RFC links to the IETF pages (like https://www.rfc-editor.org/rfc/rfc6120.html), so these should probably be swapped as well. Here is the complete log:

```
> lua compliancer -v -v compliance-suite.xml jabber-el.doap
{
        missing = {
                web = {
                        core = set{
                                "https://xmpp.org/extensions/xep-0206.html";
                                "https://www.rfc-editor.org/info/rfc7395";
                                "https://xmpp.org/extensions/xep-0124.html";
                        };
                        advanced = set{
                                "https://xmpp.org/extensions/xep-0206.html";
                                "https://www.rfc-editor.org/info/rfc7395";
                                "https://xmpp.org/extensions/xep-0124.html";
                        };
                };
                mobile = {
                        core = set{
                                "https://xmpp.org/extensions/xep-0198.html";
                                "https://xmpp.org/extensions/xep-0352.html";
                        };
                        advanced = set{
                                "https://xmpp.org/extensions/xep-0352.html";
                                "https://xmpp.org/extensions/xep-0357.html";
                                "https://xmpp.org/extensions/xep-0198.html";
                        };
                };
                core = {
                        core = set{
                                "https://xmpp.org/extensions/xep-0114.html";
                                "https://www.rfc-editor.org/info/rfc7590";
                                "https://xmpp.org/extensions/xep-0030.html";
                                "https://www.rfc-editor.org/info/rfc6120";
                        };
                        advanced = set{
                                "https://xmpp.org/extensions/xep-0114.html";
                                "https://xmpp.org/extensions/xep-0030.html";
                                "https://xmpp.org/extensions/xep-0115.html";
                                "https://xmpp.org/extensions/xep-0368.html";
                                "https://www.rfc-editor.org/info/rfc6120";
                                "https://www.rfc-editor.org/info/rfc7590";
                                "https://xmpp.org/extensions/xep-0163.html";
                        };
                };
                im = {
                        core = set{
                                "https://xmpp.org/extensions/xep-0249.html";
                                "https://xmpp.org/extensions/xep-0054.html";
                                "https://xmpp.org/extensions/xep-0280.html";
                                "https://xmpp.org/extensions/xep-0045.html";
                                "https://www.rfc-editor.org/info/rfc6121";
                                "https://xmpp.org/extensions/xep-0363.html";
                        };
                        advanced = set{
                                "https://xmpp.org/extensions/xep-0153.html";
                                "https://xmpp.org/extensions/xep-0280.html";
                                "https://xmpp.org/extensions/xep-0198.html";
                                "https://xmpp.org/extensions/xep-0045.html";
                                "https://xmpp.org/extensions/xep-0410.html";
                                "https://xmpp.org/extensions/xep-0313.html";
                                "https://xmpp.org/extensions/xep-0054.html";
                                "https://xmpp.org/extensions/xep-0363.html";
                                "https://xmpp.org/extensions/xep-0249.html";
                                "https://www.rfc-editor.org/info/rfc6121";
                                "https://xmpp.org/extensions/xep-0398.html";
                                "https://xmpp.org/extensions/xep-0223.html";
                                "https://xmpp.org/extensions/xep-0402.html";
                                "https://xmpp.org/extensions/xep-0049.html";
                                "https://xmpp.org/extensions/xep-0048.html";
                                "https://xmpp.org/extensions/xep-0191.html";
                        };
                };
                av = {
                        core = set{
                                "https://xmpp.org/extensions/xep-0215.html";
                        };
                        advanced = set{
                                "https://xmpp.org/extensions/xep-0215.html";
                        };
                };
        };
        badges = {};
        name = "jabber.el";
}
```

`compliance-suite.xml` is the current compliance suite, i.e. https://xmpp.org/extensions/xep-0479.xml

**Comment by josephmturner** [comment]
Thank you @cal0pteryx !  [Tracking here](https://codeberg.org/emacs-jabber/emacs-jabber/issues/60).

**Pull request merged**
