### PR TITLE
Add new client: Dino

### PR DESCRIPTION
**Pull request by participante0**

### CODE REVIEW

**Comment by guusdk** [comment]
You'll probably want to set the last_renewed date - otherwise the entry will be pruned from the list of clients as soon as the purge starts.

**Comment by guusdk** [comment]
Hi - that's better, but you now added renewal timestamps that are unrelated to Dino. That's the responsibility of maintainers of those software stacks (the point of having timestamps in the first place is that we want to purge entries that do not get updated by their maintainers).

**Comment by participante0** [comment]
I added only timestamps of a few active (and currently mantained) software: ChatSecure, Conversations, Converse.js, and Dino.

**Comment by guusdk** [comment]
Fair enough. Thanks for your contribution!

**Pull request merged**
