### PR TITLE
Blog post: periodic re-application of software projects

### PR DESCRIPTION
**Pull request by ge0rg**
As discussed in yesterday's board meeting

### CODE REVIEW

**Comment by guusdk** [comment]
The title is a bit to long to render nicely on one line. Also, I'd not start with a salutation, as that looks a bit weird on the overview page:
blog-1

This is the entire article. Not sure if you need a signature, as the blog template also puts your name under the post.
blog-2

**Comment by ge0rg** [comment]
I've changed the title and merged the first two paragraphs to improve the preview.

IMHO, the salutation indicates that this one is for developers, not for everybody stumbling upon our blog, though I agree it looks displaced.

Similarly with the signature, as I'm excercising a position that I don't officially own.

I'm open for suggestions regarding both.

**Comment by guusdk** [comment]
Suggestion: drop them both.

**Comment by horazont** [comment]
Maybe simply "Georg Lukas" as signature, if at all. You could consider yourself here as someone who blogs about what they read in the board meeting minutes.

**Comment by ge0rg** [comment]
Dropped both.

**Comment by guusdk** [comment]
blog-3
blog-4

**Pull request merged**
