### PR TITLE
added CC By-Sa license to the newsletter

### PR DESCRIPTION
**Pull request by goffi-contrib**
This will allow to copy the newsletter and translate it on other
websites.

I have asked commteam@ and specifically to @jcbrand  if it was OK.

### CODE REVIEW

**Comment by jcbrand** [comment]
Given that the whole site was originally licensed under CC and that the CC license will again be added site-wide, I suppose this isn't necessary anymore, right?

**Comment by goffi-contrib** [comment]
@jcbrand indeed, this P.R. is probably not needed anymore, but for now the CC 2.5 mention is not on the website, so we still can't use the newsletter on other websites.

**Comment by guusdk** [comment]
Board has discussed this in last weeks meeting. Board agrees to have the newsletter published under the Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license.

**Comment by Echolon** [comment]
All the recent Newsletters were published under 4.0, I think this can be closed.

**Comment by Echolon** [comment]
I will close this as we do so as said. Please come back if something else comes up or is treated not correctly in your view.

See for example: https://github.com/xsf/xmpp.org/blob/newsletter-july2020/content/posts/newsletter/2020-07-01.md

**Pull request closed without merging**
