### PR TITLE
Renew Mozilla Thunderbird

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew Mozilla Thunderbird

### CODE REVIEW

**Comment by Echolon** [comment]
@Neustradamus I think there is no effective development in Thunderbird regarding XMPP. If you can make a developer confirm we can do so, but I don't believe. I will close this until this changes.

**Comment by Neustradamus** [comment]
Dear @Echolon: Thunderbird supports SCRAM-SHA-256, if it is not up-to-date ;)

**Comment by Neustradamus** [comment]
@clokep: Can you comment here?

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear @mozilla, @thundernest teams, @freaktechnik, @rnons, @mkmelin, @KhushilMistry, @clokep, @aceman444, @abahmed, @aleth, @arlolra, @Harshit22, @fqueze: There is a problem to renew Mozilla Thunderbird, can you comment here?

Thanks in advance.

**Comment by freaktechnik** [comment]
@Neustradamus please don't just mention loosely associated people. If you're not sure who from the project would be best suited, there are many ways to contact the project (mailing lists, chat rooms etc.) and even if you don't directly find the correct person, you might've at least stumbled upon someone that knows about the [module owners](https://wiki.mozilla.org/Modules/Thunderbird). Further, you have given very little context in a completely foreign repository. Why does there have to be renewing? "a problem"?. I assume you refer to "no effective development", which depending on your viewpoint might not be an incorrect assessment. The XMPP protocol is maintained but new features are seldom. As an example, see this revision log: https://hg.mozilla.org/comm-central/log/tip/chat/protocols/xmpp/xmpp-base.jsm - so in the end it depends on what effective development means, and why that timestamp matters. Also, not sure what that "Others" platform refers to, the Thunderbird project officially only provides Windows, Mac OS and Linux builds (see https://www.thunderbird.net/en-US/thunderbird/all/).

**Comment by Echolon** [comment]
> @Neustradamus please don't just mention loosely associated people. If you're not sure who from the project would be best suited, there are many ways to contact the project (mailing lists, chat rooms etc.) and even if you don't directly find the correct person, you might've at least stumbled upon someone that knows about the [module owners](https://wiki.mozilla.org/Modules/Thunderbird). Further, you have given very little context in a completely foreign repository. Why does there have to be renewing? "a problem"?. I assume you refer to "no effective development", which depending on your viewpoint might not be an incorrect assessment. The XMPP protocol is maintained but new features are seldom. As an example, see this revision log: https://hg.mozilla.org/comm-central/log/tip/chat/protocols/xmpp/xmpp-base.jsm - so in the end it depends on what effective development means, and why that timestamp matters. Also, not sure what that "Others" platform refers to, the Thunderbird project officially only provides Windows, Mac OS and Linux builds (see https://www.thunderbird.net/en-US/thunderbird/all/).

Hi Martin,

thank you for your response and I apologize for the many mentionings. I already asked the person yesterday to stop this way of reaching out and it is not how we propagate this normally. So, please excuse this.

In any way, thank you for the response!

**Comment by Neustradamus** [comment]
Dear @freaktechnik, thanks for your reply :)

I have tagged you because you are a developer (like other devs): https://github.com/mozilla/releases-comm-central/search?q=xmpp&type=commits.

And it is needed to have a reply from devs to renew Mozilla Thunderbird from the XMPP website: https://xmpp.org/software/clients/.

And it is not listed here by Google: https://www.google.com/search?q=xmpp+client+list.

I am happy to read that Mozilla Thunderbird is always developed :)

This PR can be merged now!

**Comment by Neustradamus** [comment]
Dear @freaktechnik, thanks for your reply :)

I have tagged you because you are a developer (like other devs): https://github.com/mozilla/releases-comm-central/search?q=xmpp&type=commits.

And it is needed to have a reply from devs to renew Mozilla Thunderbird from the XMPP website: https://xmpp.org/software/clients/.

And it is not listed here by Google: https://www.google.com/search?q=xmpp+client+list.

I am happy to read that Mozilla Thunderbird is always developed :)

This PR can be merged now!

Note: I think that you mix me with @Echolon, I have never said that that Thunderbird has been stopped.

**Pull request closed without merging**
