### PR TITLE
Smack is used in Openfire, Strophe.js is used in Converse

### PR DESCRIPTION
**Pull request by marclaporte**

### CODE REVIEW

**Comment by guusdk** [comment]
Thanks Marc!

**Comment by guusdk** [comment]
(Also, Smack isn't used in Openfire, but hey ;-) )

**Comment by marclaporte** [comment]
oups, right. Conversations I should have said :-)

**Comment by guusdk** [comment]
(also not correct ;) )

**Comment by marclaporte** [comment]
ok, I will say nothing more :)

**Pull request merged**
