### PR TITLE
Renew JSXC

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew JSXC

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
@sualko ?

**Comment by Neustradamus** [comment]
@wurstsalat3000: https://github.com/jsxc/jsxc/releases

**Comment by Neustradamus** [comment]
@wurstsalat3000, @Echolon: https://github.com/jsxc/jsxc.

**Comment by sualko** [comment]
@Neustradamus thanks for taking care of the record.

@wurstsalat3000 that's right. We are still alive :sunglasses:

**Pull request merged**
