### PR TITLE
Add a favicon.ico and add all the other variations

### LINKED ISSUE #165: XEP pages are missing a favicon
A favicon is pretty handy to quickly identify specific browser tabs.

The main site seems to use this one: http://xmpp.org/theme/images/xmpp-logo.png

XEP html pages currently have this favicon reference:

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

but http://xmpp.org/favicon.ico is not there and returns 404.

### PR DESCRIPTION
**Pull request by lloydwatkin**
Fixes #165 ...and more :)

### CODE REVIEW

**Comment by bear** [comment]
+1 - thanks!

**Comment by guusdk** [comment]
@lloydwatkin There are a bunch of 404's in the server logs that relate to

- /apple-touch-icon-precomposed.png
- /apple-touch-icon.png

Those don't appear to be part of this PR. Should we add those too? Do you know how to generate suitable images?

**Comment by lloydwatkin** [comment]
I just used a site to generate them from the main logo. Maybe,  although
how much proprietary things should be supported is up for debate.

I can add additional resources as required but not able to test.

**Comment by bear** [comment]
you can generate them at http://iconogen.com/

**Comment by guusdk** [comment]
Your comment on "proprietary things" is valid. There is a fair number of
requests for those, so I'd be in favor for adding them.

**Comment by bear** [comment]
@guusdk can you file an issue (or update one if it's already present with the above)

**Comment by guusdk** [comment]
https://github.com/xsf/xmpp.org/issues/190

**Pull request merged**
