### PR TITLE
Arranged clients by operating system

### PR DESCRIPTION
**Pull request by conorohiggins**
I have rearranged the list from an alphabetic list of all the clients, to a list categorized by operating system.

I think this is more intuitive, and will make it easier for people to get started with XMPP, as they are coming from an existing operating system and looking for a client to fit that.

### CODE REVIEW

**Comment by guusdk** [comment]
Thanks for your contribution! 

I do wonder if this layout makes it hard to add a new client, in the future. Say that you need to add a new client somewhere in the top of the OS X column: you'd have to re-arrange the that column, but leave the other ones in place. Is there an easy way of doing that?

I don't particularly like the duplicate entries, but it doesn't bother me to much either. The "misc"  section is odd though. Those entries almost feel "left out".

**Comment by conorohiggins** [comment]
The Misc section seemed weird to me too. It's not the formatting that makes
it weird; what the hell is Asha?

Your point about rearranging columns is valid. I can't think of a way to
automatically 'push' entries down a column in markdown.

**Comment by guusdk** [comment]
@conorohiggins How would you like to proceed? The rearranging complexity is a deal-breaker for me, as it'll seriously hamper future additions to this page (but then again, no-one died and made me king of anything).

Perhaps leaving the table as-is, but making it sortable, and/or apply a filter, would bring a similar functional improvement. Both sorting as well as filtering is already in place with the table at http://xmpp.org/extensions/index.html - so that should be do-able on this page too.

**Comment by conorohiggins** [comment]
I think we should proceed by adding filtering, so people can find one
that fits their operating system. I'll look at how that's done on the
extensions page you linked to, and replicate that.

**Comment by guusdk** [comment]
@conorohiggins *poke* ;)

**Comment by conorohiggins** [comment]
What do we think of making a sortable Javascript table like the one at https://github.com/xsf/xmpp.org/blob/master/content/pages/extensions.html

**Comment by guusdk** [comment]
Go for it!

**Comment by horazont** [comment]
I think we can close this, the client listing has been completely overhauled. Grouping it by OS will be more trivial once the renewal period is over, and then we can think of nice UI. In any case, it’ll need a new PR.

**Pull request closed without merging**
