### PR TITLE
Side menus

### PR DESCRIPTION
**Pull request by guusdk**
Most pages have a menu in a side bar. Once upon a time, this side bar menu was inherited, but that mechanism now fails. To work around this problem, the sidebar definition of a set of pages is copied across many other pages. Over time, modifications sneak in that do not get copied, which makes for a messy structure.

The commits in this PR reflect my journey through discovering how things work. I ended up with replacing the very flexible, but equally complex inheritance-from-an-ancestor implementation to an implementation where the sidebar is inherited from a page that is directly referenced.

### CODE REVIEW

**Comment by guusdk** [comment]
Note that I've applied the new implementation to the first menu ("About XMPP") only! I'd like some feedback on the approach, before I apply it throughout the site.

**Comment by intosi** [comment]
I think this is a great step in the right direction, thanks for doing this!

**Comment by guusdk** [comment]
@horazont Right you are: https://github.com/xsf/xmpp.org/issues/506

**Comment by guusdk** [comment]
I have finished applying the same fix throughout the website.

**Comment by horazont** [comment]
@guusdk Did you verify that it works with the pelican version for the website? If so, hit the merge and observe whether something breaks afterwards (15 min build time). Revert if it does.

I can’t verify it locally, so I won’t hit merge.

**Comment by guusdk** [comment]
I did. It's pretty easy to run locally with the docker makefile. That pulls in the correct version of Pelican.

**Pull request merged**
