### PR TITLE
Renewed Psi/Psi+ clients

### PR DESCRIPTION
**Pull request by Ri0n**
Just in case about me (I don't if next links are publicly available. I don't have other github accounts to check)
https://github.com/orgs/psi-im/people/Ri0n
https://github.com/orgs/psi-plus/people/Ri0n

### CODE REVIEW

**Comment by guusdk** [comment]
Thanks for your contribution! I'm not sure what you'd like us to do with the account names that you provided though.

**Comment by Ri0n** [comment]
well, I thought only a project's owner can make such a pull request. and I'm the current owner of Psi and Psi+.

**Comment by guusdk** [comment]
Some people might be more strict in accepting PRs than I am. ;)

**Comment by horazont** [comment]
FWIW, we don’t enforce the project owner rule (if there even is one). At least I don’t. I like to ask why they add a client if they’re not the owner, but usually I don’t have to because the client has enough info on the website to make sense.

**Comment by Kev** [comment]
The reason for that rule was mostly to stop one person going around and submitting a tonne of things unbeknownst to the owners.( "I think the list should have all these things on it, and I'm adding them all" type people). It doesn't really need strict enforcing, but that's the rationale.

**Pull request merged**
