### PR TITLE
Mention MongooseIM 4.0 release and the corresponding links

### PR DESCRIPTION
**Pull request by erszcz**
[MongooseIM 4.0](https://github.com/esl/MongooseIM/releases/tag/4.0.0) has been released at the beginning of October. This is an update about the release and some corresponding articles on the topic.

### CODE REVIEW

**Comment by Echolon** [comment]
Thank you for your commit!

Can you put the links has hyperlinks?

`[Text](Link)`

**Comment by erszcz** [comment]
@Echolon Sure, here it is :+1:

**Comment by Echolon** [comment]
@erszcz Thanks for changeing! However I think we need to stick to the Pelican readable format (not Markdown).

It's like this: [my text](my link)

**Review by Echolon — APPROVED** [review]
I edited it myself - thanks for your contribution!

**Comment by erszcz** [comment]
Hi @Echolon! Sorry for keeping you waiting, I was away for the weekend. Thank you for doing the edit!

**Pull request merged**
