### PR TITLE
Renew Apache Vysper entry

### PR DESCRIPTION
**Pull request by reda-alaoui**

### CODE REVIEW

**Comment by guusdk** [comment]
Vysper seems to have been dormant since 2013. Although I'm unfamiliar with the project, I wonder if this reflects in the usability of this project. Is this something that the XSF should list on its website?

**Comment by reda-alaoui** [comment]
@guusdk , yes it has been dormant.
I am currently trying to resurrect it.

I have been searching for a project like Vysper for a month. I could not find neither on Google Search or xmpp.org. I decided to create my own java xmpp server framework. The first thing I needed was a solid library to manage TCP connections, so I found Apache Mina. And looking at its [website](https://mina.apache.org/), by pure chance, I found Apache Vysper !

If people like me can't find Vysper during their search for solutions, Vysper has zero chance of being successfully rebooted.

**Comment by guusdk** [comment]
I applaud your effort to revive the project! If anything, it'll give users more options, which is a good thing!

However, the XSF website is not intended to be a tool to make projects successful. Instead, it tries to help people by listing useful projects. 

If Vysper is a non-dead project, I see no problem listing it - but as there has not been _any_ activity for about 6 years, I'm unsure if it's going to be of any help.

Can we agree to add this project, after the project has seen renewed activity?

**Comment by reda-alaoui** [comment]
My first pull request was just merged in https://github.com/apache/mina-vysper
Could we consider that as a renewed activity?

**Comment by Nyco** [comment]
It seems to Vysper is now awake: https://github.com/apache/mina-vysper/commits/master

**Comment by guusdk** [comment]
Indeed!

**Pull request merged**
