### PR TITLE
Add even more test tools

### PR DESCRIPTION
**Pull request by Zash**
- search and observe.jabber.network by @horazont 
- account exporter by @mwild1 
- badxmpp tls etc test thing by @Zash 

(Should be enough pings to give them a chance to object, in case I'm taking liberties in adding things I'm not the author of to the listing)

### CODE REVIEW

**Comment by Echolon** [comment]
merging somehow doesnt work for me

**Comment by Echolon** [comment]
merging somehow doesnt work for me

**Comment by Zash** [comment]
Did I confuse github by reusing a branch name? Got a :unicorn: at first...

**Comment by Zash** [comment]
a50888580b5bbd921a8aae669a74fdb50b7c0243 looks like it tho?

**Comment by Echolon** [comment]
Dunno what happened

**Pull request merged**
