### PR TITLE
Update client.json

### PR DESCRIPTION
**Pull request by yagiza**
Add information about eyeCU client.
Update information about Psi and Sim-IM clients.

### CODE REVIEW

**Comment by guusdk** [comment]
I remain reluctant to add OS/2 as a platform. Clients listed here only appear to support that when they're multi-platform. I'd like opinion of others, before rejecting or accepting this PR.

In the mean time, it might be good to separate this PR into two: one that updates the client registration, and one that updates the platform. That will allow us to process both PRs separately.

**Comment by SamWhited** [comment]
OS/2 hasn't had a release since the early 2000's as far as I am aware; I also see no point in adding it to the list.

**Comment by horazont** [comment]
@yagiza Realistically, splitting the PR into two will help at least the renewal to pass. We haven’t come to a conclusion whether we want OS/2 on the list or not yet.

**Comment by yagiza** [comment]
Ok. I removed mention of "OS/2" from this PR, replacing it with "Other".

**Comment by yagiza** [comment]
> OS/2 hasn't had a release since the early 2000's as far as I am aware; I also see no point in adding it to the list.
I just want to notice, that "OS/2" platform include not only IBM OS/2, which support and development ended many years ago, but also its decendants, deployed under license of IBM:

- eComStation from Serenity System International (lst release was in 2013)
- ArcaOS AKA Blue Lion (first release planned on 15.04.2017)

**Pull request merged**
