### PR TITLE
Update Tigase Clients as updated files

### PR DESCRIPTION
**Pull request by Dwisnewski**
Change "last-renewed" for Tigase clients to current date as well as add new versions of iOS and Android to clients list.

### CODE REVIEW

**Comment by guusdk** [comment]
Continuous Integration fails to build this PR. I'm not exactly sure why. I've never seen a github diff use red letters. Did you use an incompatible character encoding?

**Comment by Dwisnewski** [comment]
Nothing different that I'm aware of, I just used the field to push the replacement.  Let me check the push again.

**Comment by Dwisnewski** [comment]
I found the errors, it was a problem with syntax did not close the "platforms" container properly which led to the issue, 2nd commit should fix now.

**Comment by Dwisnewski** [comment]
Bad formatting errors, forgot that single lines in brackets do not need terminating commas.  Document should be good to go now.

**Comment by guusdk** [comment]
Hmm, could you replace this with a single, link that refers to both platforms? I'd like to avoid having a list that lists some clients individually (per platform), while others do not. That'll lead to a tug of war, I'm afraid.

**Comment by guusdk** [comment]
Gracias

**Pull request merged**
