### PR TITLE
Added an entry for UWPX

### PR DESCRIPTION
**Pull request by COM8**
Added the UWPX XMPP client.

### CODE REVIEW

**Comment by guusdk** [comment]
Hey, thanks for your contribution. I think you've manually modified the json file - which is fine, but often leads to errors that will cause our parser to fail. Please address the errors as reported by Travis:

> ERROR: entry 'UWPX': should be placed behind 'Zom' (all entries must be ordered alphabetically by case-folded name)
> ERROR: entry 'UWPX': undefined platforms: 'Windows 10 (UWP)' (the allowed platforms are listed in platforms.json. If you think a platform is missing add it and mention it in your Pull Request)
> Found 2 severe violations. Please fix them.

Also, its website lists the client as an early Alpha. I'm reluctant to add non-feature complete clients to our list, as that's likely to disappoint users. Perhaps we should add this client only after the first proper release?

**Comment by horazont** [comment]
(note that the error message is unclear and UWPX should be placed **in front of** Zom, not behind.)

**Comment by COM8** [comment]
Ok, thanks I will creata a new pull request once UWPX reached the stable phase.
 > (note that the error message is unclear and UWPX should be placed in front of Zom, not behind.)

If you follow the [documentation](https://github.com/xsf/xmpp.org/blob/master/data/README.rst) it says:
> [...] Insert it into the top-level JSON Array as **last** element by [...]

😉

**Comment by horazont** [comment]
@COM8 The same documentation also says (boldface mine):

> Insert it into the top-level JSON Array as last element by adding a comma after the last , and then pasting the above template with your modifications. **Use the tool as described** in the previous section to perform a renewal (**this will sort the list correctly** to minimize future diffs).

And in the next paragraph (boldface original, emphasis mine):

> **If you do not use the tool**, make sure that you set the ``last_renewed`` key manually to the current date (as seen in other entries) in UTC and _adhere to the sorting requirements of the JSON file_. You can use the ``lint-list.py`` tool to verify that everything is in order. If ``lint-list.py`` complains, the Travis CI will reject your Pull Request.

😉

**Pull request closed without merging**
