### PR TITLE
REVIEW: The XMPP Newsletter August 2024

### PR DESCRIPTION
**Pull request by nemmig**
# XMPP Newsletter

## This is the draft for the next release covering August 2024

*Final release is planned for 5th Sept 2024.* 

Contributions are much appreciated. You don't need any technical knowledge to contribute. If you need help, please ask in the Communication-Team group chat: [commteam@muc.xmpp.org](mailto:commteam@muc.xmpp.org).

If you would like to add news, that's possible via:

- Using our [online Pad](https://pad.nixnet.services/oHnY_ZvLT8SoFyCqIC2ung) **(Pad is closed for May 2024!)**
- Adding your content to this pull request's thread (i.e. a comment below)
- Creating a pull request
- Posting something in our XMPP channel (xmpp:[commteam@muc.xmpp.org](mailto:commteam@muc.xmpp.org)?join)

It's really helpful if you try to give a short summary (<5 lines) of your contribution or of what the link you're posting is offering. You don't need to write in a formal tone - just be passionate about why this motivates you or about what you are working on!

| During the month | 1st - 2nd of the month | 3rd - 4th of the month | 5th of the month |
|--------------|-----------|------------|------------|
| Create Draft in Pad & GitHub | Last Call for final edits     | Review phase        |RELEASE! :rocket:|
| Collect news & highlights      |  |  Translators can start working      | |
| Reminder mid-month + end of month      |  |        ||

## Status

- [x] Collection of news
- [x] Review
- [ ] Blog post + Newsletter mail (use `tools/newsletter_email.py` after the post has been published)
- [ ] Social media
- [ ] Translations

### CODE REVIEW

**Comment by Echolon** [comment]
@nemmig I did some changes: https://github.com/xsf/xmpp.org/pull/1427/commits/12becaa7c120872a8ac72236c5c75ccf18288ce2
 
 Let me know if you disagree. Also some changes for the next time to consider.
 
 But to be clear: Really great job and preparation!

**Comment by Echolon** [comment]
@nemmig could you put the translation of the newsletter always in a separate PR?

That helps to push forward the main release.

**Comment by nemmig** [comment]
> @nemmig could you put the translation of the newsletter always in a separate PR?
> 
> That helps to push forward the main release.

Sure thing!
I created a new branch and PR for this matter: https://github.com/xsf/xmpp.org/pull/1431
Will always keep the translation on a separated PR from now on.
Thank you!!

**Comment by nemmig** [comment]
> @nemmig I did some changes: [12becaa](https://github.com/xsf/xmpp.org/commit/12becaa7c120872a8ac72236c5c75ccf18288ce2)
> 
> Let me know if you disagree. Also some changes for the next time to consider.

No complains on this side!.
I was actually counting on you doing the editorial review and changes!

> But to be clear: Really great job and preparation!

Thank you very much for your kind words!
It's been a pleasure for me to help!
Thanks for giving me the chance! \o/

**Comment by Echolon** [comment]
## Editorial closing of the XMPP Newsletter August '24 release

Many thanks to all supporters in this story!

- English (original): [xmpp.org](https://xmpp.org/categories/newsletter/)
  - General contributors: *Adrien Bourmault (neox), Alexander "PapaTutuWawa", Arne, cal0pteryx, emus, Federico, Gonzalo Raúl Nemmi, Jonas Stein, Kris "poVoq", Licaon_Kter, Ludovic Bocquet, Mario Sabatino, melvo, MSavoritias (fae,ve), nicola, Schimon Zachary, Simone Canaletti, singpolyma, XSF iTeam*
- French: [jabberfr.org](https://news.jabberfr.org/category/newsletter/) and [linuxfr.org](https://linuxfr.org/tags/xmpp/public)
  - Translators: *Adrien Bourmault (neox), alkino, anubis, Arkem, Benoît Sibaud, mathieui, nyco, Pierre Jarillon, Ppjet6, Ysabeau*
- Italian: [notes.nicfab.eu](https://notes.nicfab.eu)
  - Translators: *nicola*
- Spanish: [xmpp.org](https://xmpp.org/categories/newsletter/)
  - Translators: *Gonzalo Raúl Nemmi*
- German: [xmpp.org](https://xmpp.org/categories/newsletter/)
  - Translators: *Millesimus*

❤️ 🎆 Next release will be next month on 5th of October 2024!

Have a good time until then and see you soon!

**Pull request merged**
