### PR TITLE
Apply for trademark sublicense for JabberCat

### PR DESCRIPTION
**Pull request by horazont**
The personal details have been supplied to trademark@jabber.org, hopefully reaching @stpeter as intended. If not, please let me know via email (jonas@wielicki.name) or other means.

(See also #200, if you’re wondering on why this PR was made and how that fits into the trademark process.)

### CODE REVIEW

**Comment by stpeter** [comment]
I've forwarded this to the board list so they can put it on an agenda.

**Comment by horazont** [comment]
Since Board has asked why they are involved in this decision, here’s why I think it is: 

1. @stpeter as trademark contact and from my understanding the most knowledgable person on the trademark process said so.

2. #200 was handled in the same manner, where @stpeter mentioned that the XSF Board of Directors is the Trademark Comittee referenced in [the decision process](https://xmpp.org/about/xsf/jabber-trademark/license-decision-process.html).

So unless something changed since 2016 on who is responsible for deciding on Trademark Sublicense  requests (I currently do not have the time to research that and have to rely on what @stpeter says), I think the Board is still in the position to decide.

On the question if a sublicense for an Open Source Project needs approval, I think this is fairly clear in the [usage guidelines (section 2.1)](https://xmpp.org/about/xsf/jabber-trademark/usage-guidelines.html):

> JABBER may be used in the name of software products licensed under an OSI approved open source license (e.g. GPL, JOSL) providing that:
> 
> *    An application to use the trademark has been completed (from the XSF web site).
> *    It has received a license to use the trademark from the XSF.
> […]

**Comment by stpeter** [comment]
@horazont That is all correct!

**Comment by horazont** [comment]
Decided by [board on todays meeting](https://mail.jabber.org/pipermail/members/2017-September/008648.html):

> 3.2) Trademark sublicense for JabberCat
> 
> The Board approved the sublicense as requested in https://github.com/xsf/xmpp.org/pull/358

**Pull request merged**
