### PR TITLE
Renew Metronome's entry

### PR DESCRIPTION
**Pull request by maranda**

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
Would you be interested in publishing a DOAP file for Metronome? We started rendering those on xmpp.org's software section, like for example here: https://xmpp.org/software/servers/prosody-im/

**Comment by maranda** [comment]
@wurstsalat3000 but I'm not knowledgeable about the format myself

**Comment by wurstsalat3000** [comment]
You can find the source for Prosody's DOAP file here for example: https://hg.prosody.im/trunk/file/tip/doc/doap.xml

It's basically search and replace/remove. I found this very helpful in documenting supported extensions. You can also host and render the DOAP file yourself, if you want, like here: https://gajim.org/support/extensions/

Allowed fields for XMPP-specific fields can be found at: https://linkmauve.fr/ns/xmpp-doap

**Comment by wurstsalat3000** [comment]
There is now a hosted DOAP file available for Metronome IM at xmpp.org, see 06a335b1810c2d47990832cebc8d4e704b2e59e8

I added this in order to migrate from the old data store. Feel free to add your own file, if you want to replace this one.

**Comment by maranda** [comment]
Gotcha will look into it as sono as I have the chance

**Comment by maranda** [comment]
> There is now a hosted DOAP file available for Metronome IM at xmpp.org, see [06a335b](https://github.com/xsf/xmpp.org/commit/06a335b1810c2d47990832cebc8d4e704b2e59e8)
> 
> I added this in order to migrate from the old data store. Feel free to add your own file, if you want to replace this one.

Okay before I start to compile it I'll wait to release v4, which is under testing and soon due out.

**Pull request merged**
