### PR TITLE
Update MatriX and add XmppDotNet libraries

### PR DESCRIPTION
**Pull request by agnauck**
* remove invalid doap link which hopefully fixes the lib to show up in the list
* Replace MatriX vNext with XmppDotNet after the name of the lib changed

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
Hi @agnauck ! Both MatriX and MatriX vNext are listed under "Libraries" (if "All Platforms" is selected). By removing links to their DOAP files, both libraries will be listed in "Other Software" at the bottom. I'm not sure if that's what you actually wanted?

**Comment by agnauck** [comment]
@wurstsalat3000 OK, I will revert the DOAP stuff. I did not know that somehow a minimal DOAP file gets auto generated.

**Comment by guusdk** [comment]
Ah, sorry for jumping the gun here.

**Comment by wurstsalat3000** [comment]
At the point where we switched away from "last_updated", I manually added a hosted DOAP file for each client which was regularly updated in the past. See https://github.com/xsf/xmpp.org/tree/master/static/hosted-doap These DOAP files contain all infos from their previous keys in `software.json`.

If you like, I can add back both links and adjust both DOAP files to your updates.

**Comment by wurstsalat3000** [comment]
By adding `<os>Windows</os>` to https://github.com/xsf/xmpp.org/blob/master/static/hosted-doap/matrix.doap you would see MatriX appear in "Libraries" with "Windows" selected for (just an example).

**Comment by agnauck** [comment]
thanks for clarification. I will make another PR then and also rename the matrix-vnext.doap to xmppdotnet.doap shortly if that works.

I am looking more into doap stuff soon and will verify how it can be integrated my current build processes.

**Comment by wurstsalat3000** [comment]
> I am looking more into doap stuff soon and will verify how it can be integrated my current build processes.

Ping me in commteam@ if you need any help regarding DOAP files 👍

**Pull request merged**
