### PR TITLE
Update clients.json

### PR DESCRIPTION
**Pull request by rockliffe**
Update AstraChat entry.

### CODE REVIEW

**Comment by rockliffe** [comment]
Please post the update to the live site.

**Review by Echolon — APPROVED** [review]
@rockliffe thanks for your PR.

But please have some patience as this is done by volunteers.

**Comment by wurstsalat3000** [comment]
@rockliffe the `version` attribute refers to the XEP version implemented by the software. You added the client's (AstraChat) version instead. Please either remove all version attributes, or change it to the implemented XEP versions. For reference: https://linkmauve.fr/ns/xmpp-doap

Here is an example where the `version` attribute is set wrongly, but this affects all XEPs listed:

```xml
<implements>
<xmpp:SupportedXep>
<xmpp:xep rdf:resource="https://xmpp.org/extensions/xep-0030.html"/>
<xmpp:status>complete</xmpp:status>
<xmpp:version>1.6</xmpp:version>
</xmpp:SupportedXep>
</implements>
```

**Comment by Echolon** [comment]
> @rockliffe the `version` attribute refers to the XEP version implemented by the software. You added the client's (AstraChat) version instead. Please either remove all version attributes, or change it to the implemented XEP versions. For reference: https://linkmauve.fr/ns/xmpp-doap
> 
> Here is an example where the `version` attribute is set wrongly, but this affects all XEPs listed:
> 
> ```
> <implements>
> <xmpp:SupportedXep>
> <xmpp:xep rdf:resource="https://xmpp.org/extensions/xep-0030.html"/>
> <xmpp:status>complete</xmpp:status>
> <xmpp:version>1.6</xmpp:version>
> </xmpp:SupportedXep>
> </implements>
> ```

https://github.com/xsf/xmpp.org/issues/1198

**Comment by rockliffe** [comment]
Thanks @Echolon, we've fixed the DOAPs.

**Pull request merged**
