### PR TITLE
Renew Psi/Psi+

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew Psi/Psi+

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
@Neustradamus please ask an author to comment here, otherwise I'll close this PR within a week.

**Comment by wurstsalat3000** [comment]
Same goes for all the other renewal PRs.

**Comment by wurstsalat3000** [comment]
@Ri0n ?

**Review by Ri0n — APPROVED** [review]

**Comment by Echolon** [comment]
@Ri0n also suggestion for you to place DOAP files. We will soon better promote clients in the new website setup.

**Comment by Ri0n** [comment]
@Echolon I hope @Neustradamus will make a PR with it :)

**Pull request merged**
