### PR TITLE
Uses/IM: correct nimbuzz link, old one is 404

### PR DESCRIPTION
**Pull request by ge0rg**

### CODE REVIEW

**Comment by guusdk** [comment]
Hmm, I'd be very cautious to refer to this page. As far as I know, Nimbuzz has ceased to exist completely. I'm not sure who is serving what content at the domain that you're adding here.

**Comment by ge0rg** [comment]
Indeed, all I did was a cursory look and it seemed at least to match the spirit. Should we remove Nimbuzz altogether, then?

**Comment by guusdk** [comment]
Yes, I think so. There's little value in showing off a use-case that doesn't exist any more.

**Comment by Ppjet6** [comment]
Can this be closed then?

**Comment by ge0rg** [comment]
Alright, I've just killed Nimbuzz completely. Feel free to apply PR if appropriate :)

**Comment by guusdk** [comment]
Works for me! Thanks!

**Pull request merged**
