### PR TITLE
add blabber.im client

### PR DESCRIPTION
**Pull request by Dominion0815**

### CODE REVIEW

**Comment by Echolon** [comment]
@SeveFP do you see what fai'ed?

**Comment by guusdk** [comment]
It's an ordering thingy:

> ERROR: entry 'BeagleIM by Tigase, Inc.': should be placed in front of 'blabber.im' (all entries must be ordered alphabetically by case-folded name)

**Comment by Echolon** [comment]
Thank you @guusdk

**Comment by Fhiss** [comment]
Hello. I don't still see blabber.im on the https://xmpp.org/software/clients/.

**Comment by Echolon** [comment]
@Fhiss the project developer has to update the timestamp once a year

**Comment by Fhiss** [comment]
Thanks. Can I do it or only the developer?

**Comment by Echolon** [comment]
> Thanks. Can I do it or only the developer?

Yes, but to merge we need the confirmation by the dev

**Pull request merged**
