### PR TITLE
#176: 'projects' moved to 'uses'.

### PR DESCRIPTION
**Pull request by guusdk**
As discussed in #176: (Software -> Projects) page content should be moved to various pages under "Uses"

### CODE REVIEW

**Comment by bear** [comment]
I'll work on the redirect and merge this.

@guusdk any reason you changed the structure from a table to a simple list? Seems easiest to retain the table along with all of the extra data the table has.

**Comment by guusdk** [comment]
Not really. The existing pages under 'uses' did not have a table, so I kept
that layout. I have no preference either way.

**Comment by bear** [comment]
If you have time can you add it back? (or I will later)

thanks!

**Comment by guusdk** [comment]
No problem, but later. I'm on a mobile phone now. I'll race you to the PR.
:)

**Comment by guusdk** [comment]
I've modified the listing on the two pages to which I added the content from 'projects'. I'm not sure if this is an improvement though. I'll leave final say to you.

**Comment by bear** [comment]
👍  merging

**Comment by tfar** [comment]
Running `make html` i receive the following error:

```
 ~/D/xmpp.org:master> make html
pelican /Users/tobias/Development/xmpp.org/content -o /Users/tobias/Development/xmpp.org/output -s /Users/tobias/Development/xmpp.org/pelicanconf.py
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: Empty alt attribute for image delirium.jpg in /Users/tobias/Development/xmpp.org/content/posts/blog/brussels-trip-report.md
WARNING: Empty alt attribute for image devroom-summit10.jpg in /Users/tobias/Development/xmpp.org/content/posts/blog/brussels-trip-report.md
WARNING: Empty alt attribute for image dinner-summit10.jpg in /Users/tobias/Development/xmpp.org/content/posts/blog/brussels-trip-report.md
WARNING: Empty alt attribute for image xmppwg-summit10.jpg in /Users/tobias/Development/xmpp.org/content/posts/blog/brussels-trip-report.md
WARNING: Other images have empty alt attributes
WARNING: There are 2 variants of "xmpp-standards-foundation-xsf" with lang en
WARNING: 	/Users/tobias/Development/xmpp.org/content/pages/about/xmpp-standards-foundation.md
WARNING: 	/Users/tobias/Development/xmpp.org/content/pages/about/xsf/council-policies-and-procedures.md
CRITICAL: UndefinedError: 'pelican.contents.Page object' has no attribute 'dropdown_menu_elem_url_4'
make: *** [html] Error 1
```

**Comment by guusdk** [comment]
:(

That's a result of me not building things locally before committing. I assumed that Travis would pre-preemptively validate the PR. 

Fixed here: https://github.com/xsf/xmpp.org/pull/179

**Pull request merged**
