### PR TITLE
Renew Xabber Android

### PR DESCRIPTION
**Pull request by Str4tocaster**

### CODE REVIEW

**Comment by guusdk** [comment]
@horazont Can you explain why this PR makes Travis unhappy? I'm not seeing anything wrong with it.

**Comment by Str4tocaster** [comment]
@guusdk It looks like my Travis configuration is just missing environment variables for python.

**Comment by Str4tocaster** [comment]
@guusdk What about this PR?

**Comment by guusdk** [comment]
I'd like it to pass the Travis build, before we hit merge. I'm concerned that otherwise, the website build might break.

**Comment by Str4tocaster** [comment]
@guusdk You right it was my mistake. Now it looks good. Accept this PR, please.

**Comment by guusdk** [comment]
Thanks! I looked, but couldn't find that problem :)

**Pull request merged**
