### PR TITLE
DRAFT: [newsletter] Update XEP section

### PR DESCRIPTION
**Pull request by wurstsalat3000**
@Echolon

### CODE REVIEW

**Review by Echolon — APPROVED** [review]
Thanks a lot!

**Comment by Echolon** [comment]
@wurstsalat3000 would be a nice service to link to the regarding mailing list if people are interested?

**Comment by wurstsalat3000** [comment]
This PR was intentionally set to DRAFT, so I can update this until the end of the month :) I’ll open another one if there are more updates this month.

**Comment by wurstsalat3000** [comment]
> @wurstsalat3000 would be a nice service to link to the regarding mailing list if people are interested?

Yep, I’ll add a link with the next PR.

**Comment by Echolon** [comment]
😨 ouh sorry - just ran through all the PRs and havent realized 🙈

Shall I revert?

**Comment by wurstsalat3000** [comment]
No, it’s alright!

**Pull request merged**
