### PR TITLE
Add Pade client

### PR DESCRIPTION
**Pull request by wrooot**

### CODE REVIEW

**Comment by guusdk** [comment]
{quote}ERROR: entry 'Pidgin': should be placed in front of 'Pàdé' (all entries must be ordered alphabetically by case-folded name)
Found 1 severe violations. Please fix them.{quote}

Apparently, 'à' comes after, not before 'i' in the code that we use for our website.

**Comment by wrooot** [comment]
Swapped them

**Comment by wrooot** [comment]
Same error. I think i should put it to the bottom of the list of P

**Comment by wrooot** [comment]
Fine now

**Comment by guusdk** [comment]
Thanks!

**Pull request merged**
