### PR TITLE
Update XEPs

### PR DESCRIPTION
**Pull request by wurstsalat3000**
@Echolon just merge this PR at the end of the month. I’ll edit this one as soon as XEP updates arrive.

### CODE REVIEW

**Comment by Echolon** [comment]
This is still WIP?

**Comment by wurstsalat3000** [comment]
No it's finished, please merge!

Am 30. Oktober 2020 16:07:10 MEZ schrieb Echolon <notifications@github.com>:

**Comment by Echolon** [comment]
Ah okay. You always set a draft PR to "Ready for review"

**Review by Echolon — APPROVED** [review]
Great summary again!

**Pull request merged**
