### PR TITLE
Add opendomain.org attribution

### LINKED ISSUE #497: Xmpp.Org should include a attribution link to OpenDomain
I donated the domain Xmpp.Org to the Jabber Software Foundation.  In return, they agreed to link to OpenDomain.Org 

Please see:
https://web.archive.org/web/20070504093558/https://xmpp.org/xsf/press/2005-12-30.shtml

OpenDomain is a non profit project the supports Open Source.  The link request is to raise awareness of the project - we do not have advertising.  The link request is the same as all open source that requires all forks to include a copy of the license file.

### PR DESCRIPTION
**Pull request by horazont**
Fixes #497.

Desktop Screenshot:
screen shot 2019-01-31 at 17 04 34

Mobile Screenshot:
screen shot 2019-01-31 at 17 04 29

### CODE REVIEW

**Comment by opendomain** [comment]
Looks awesome. Thank you

**Comment by guusdk** [comment]
Thanks Jonas!

**Comment by opendomain** [comment]
broken link

**Comment by guusdk** [comment]
Oops. Fixed in #515. The website doesn't appear to be exposed through https. Is that intentional?

**Pull request merged**
