### PR TITLE
Renew profanity

### PR DESCRIPTION
**Pull request by Ppjet6**
@jubalh, can I get an ACK please :)

Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

### CODE REVIEW

**Comment by jubalh** [comment]
@Ppjet6 actually I have no idea what this is about :-)
Can you explain to me even though it got already merged?

**Comment by Ppjet6** [comment]
It makes you appear in the following list: https://xmpp.org/software/clients.html

**Comment by Ppjet6** [comment]
See also https://xmpp.org/2017/03/new-xmpp-software-listing-rules/

**Comment by jubalh** [comment]
I see. Thanks for doing this!

**Pull request merged**
