### PR TITLE
Update software _index.md

### PR DESCRIPTION
**Pull request by Echolon**
I would love to see it like this still

### CODE REVIEW

**Comment by cal0pteryx** [comment]
Could you explain why?

**Comment by Echolon** [comment]
> Could you explain why?

Yes, because noone will find and use it like this. The list is very long.

**Comment by cal0pteryx** [comment]
You moved the "Legacy Software" list above the DOAP software listing. Legacy entries should be displayed further down, not right at the top.

**Comment by Echolon** [comment]
> You moved the "Legacy Software" list above the DOAP software listing. Legacy entries should be displayed further down, not right at the top.

Oh okay. So what I want is this up:

Screenshot_20231024_194718

**Pull request merged**
