### PR TITLE
add monocles chat to doap file

### PR DESCRIPTION
**Pull request by 12aw**
PR to for monocles chat in doap file

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
@12aw I'm sorry, I think I caused some confusion here.
#986 is a draf PR, which enables rendering a client list _from_ DOAP files. This PR is not finished yet.

What I asked for was to simply provide a link to monocles chat's DOAP file, so it can _later_ be used for #986

Looking at https://codeberg.org/Arne/monocles_chat I don't see any DOAP file to link to. If you provide me a link, I'll add it for you.

**Comment by 12aw** [comment]
Ah, thanks. Like this? https://codeberg.org/Arne/monocles_chat/src/branch/master/monocles_chat.doap
:)

**Comment by wurstsalat3000** [comment]
Yes, but you should change the name element as well ;)

Please refer to https://linkmauve.fr/ns/xmpp-doap for guidance on how to fill out the elements. For example, you filled "status" with "wip" in one occasion. But the specification says: "Can be 'complete', 'partial', 'planned', 'deprecated', 'removed' or 'wontfix'"

**Comment by 12aw** [comment]
thanks for the fast check! Now it should be better

**Comment by wurstsalat3000** [comment]
Added in 6f4a51bf42335744959c4ccbddfb1acdfaf3f4e0

**Pull request closed without merging**
