### PR TITLE
Attempt to be more end-user friendly by providing a little bit of additional info

### PR DESCRIPTION
**Pull request by pmaziere**

### CODE REVIEW

**Comment by Echolon** [comment]
Hi guys,

is this ready to merge? 

You can always create draft pull requests, too!

**Comment by wurstsalat3000** [comment]
@pmaziere re Gajim 1.2.1 release paragraph: Thank you for the improvements!

One thing though: 'Audio/Video calls are working again' - we are not there yet. There have been code improvements, but it is not working yet (that’s why it’s listes in 'Known issues'). I’d cross that last sentence.

**Comment by Echolon** [comment]
Hi guys, shall I merge this now?

**Comment by pmaziere** [comment]
@Echolon : if my last correction fits @wurstsalat3000 requirements, then I guess you can merge

**Pull request merged**
