### PR TITLE
Renew MongooseIM

### PR DESCRIPTION
**Pull request by Neustradamus**
Renew MongooseIM

### CODE REVIEW

**Comment by Echolon** [comment]
@erszcz

**Comment by Neustradamus** [comment]
Dear @esl, @chrzaszcz, @arcusfelis, @NelsonVides, @michalwski, @janciesla8818, @fenek: There is a problem to renew MongooseIM, please comment here.

**Review by chrzaszcz — APPROVED** [review]
Looks good to me, MongooseIM is very actively maintained and developed and I think it should be renewed for sure!

**Review by NelsonVides — APPROVED** [review]
MongooseIM is indeed developing and fast-evolving!
LGTM, thanks for the update! 😄

**Comment by Echolon** [comment]
The same here: Thank you for your response but I apologize for the many mentionings. I already asked the person yesterday to stop this way of reaching out. It is not how we propagate this normally. So, please excuse this.

If there is anything else to discuss feel free to reach out to me, here or in one of the XSF group chats (MUC - I assume you know actually).

**Comment by erszcz** [comment]
Hey, @Echolon! Sorry for not responding yesterday, I was trying to keep away from the computer since it was the weekend - yet I wanted to address this early this morning. The guys beat me to it, though! Thanks for keeping us in the loop 👍

**Comment by Echolon** [comment]
> Hey, @Echolon! Sorry for not responding yesterday, I was trying to keep away from the computer since it was the weekend - yet I wanted to address this early this morning. The guys beat me to it, though! Thanks for keeping us in the loop 👍

Okay great - Yes, keep the balance please :-)
Looking forward!

**Comment by Neustradamus** [comment]
Thanks @esl team, @chrzaszcz, @erszcz: You know that I am always happy to contribute and help XMPP projects like yours ;)

**Pull request merged**
