### PR TITLE
[newsletter] Add Movim news

### PR DESCRIPTION
**Pull request by wurstsalat3000**
@Echolon

### CODE REVIEW

**Comment by Echolon** [comment]
@wurstsalat3000 thank you for the efforts today!

There seems to be a conflict, can you elaborate on this?

**Review by Echolon — CHANGES_REQUESTED** [review]
There seems to be a conflict, can you elaborate on this?

**Comment by wurstsalat3000** [comment]
Should be good now.

**Comment by Echolon** [comment]
Perfecto!

**Pull request merged**
