### PR TITLE
Announce MongooseIM 3.7.1

### PR DESCRIPTION
**Pull request by erszcz**
Hi! This announces the latest MongooseIM 3.7.1 and also mentions 3.7.0 that we forgot to PR in May. I hope it's not taking too much space ;)

### CODE REVIEW

**Comment by Echolon** [comment]
Hi @erszcz,

thank you for providing the information!

One question: There has been blog post from Mongoose as well this month. Would you mind to add them to with some explanation for readers to the Article section as well? That would be nice!

Some one already reach us in the group but I haven't found time to add it.

> Our newest release 3.7.1https://github.com/esl/MongooseIM/releases
And a load-testing blog that showed how our XMPP server could handle almost 2.5 million connections, passing 45 thousand messages per second. We believe with further testing that we could easily show the server handling 10 million connections. 
https://www.erlang-solutions.com/blog/scaling-a-mongoose-how-scalable-is-the-mongooseim-xmpp-server.html

Anyway, I can just merge your PR if you don't have time or motivation.

**Comment by erszcz** [comment]
Ahhh, I haven't noticed there's a separate "Articles" section. I'll edit the entries appropriately tomorrow morning. Thanks for the pointers!

**Comment by Echolon** [comment]
Sure, no rush. Thank you!

**Comment by erszcz** [comment]
I've updated the PR with a slightly longer mention of the scalability blog post. Let me know, please, if I can help in any other way :)

**Comment by Echolon** [comment]
Thank you very much - highly appreciated!

If you have other news in the future, feel free to create a PR again!

**Pull request merged**
