### PR TITLE
data/software.json: specify platforms of Smack

### PR DESCRIPTION
**Pull request by Flowdalic**

### CODE REVIEW

**Comment by cal0pteryx** [comment]
Hi @Flowdalic ! Platforms for Smack are listed in its DOAP file directly, see https://github.com/xsf/xmpp.org/blob/master/static/hosted-doap/smack.doap#L10

You can add as many `<os>` tags as you like.

Once there is a DOAP file for a project, the listing in software.json shouldn't contain any more info than the project's name.

Even better would be if the project adopted (and extended) the DOAP file hosted at this repo :)

**Comment by Flowdalic** [comment]
@cal0pteryx thanks for your reply.

Would deleting static/hosted-doap/smack.doap also be an option to achieve what I want to achieve (i.e., that Smack shows up when either 'Android', 'Linux', 'Windows', or 'macOS' is selected on the webpage)?

**Comment by cal0pteryx** [comment]
Only projects with a DOAP file are listed in the filterable software overview. DOAP-less projects are listed in the legacy table at the very bottom of that page.

**Comment by Flowdalic** [comment]
@cal0pteryx Thanks again for your reply. I've updated the doap file also.

**Comment by Flowdalic** [comment]
Hmm, not sure why the CI is failing

**Pull request merged**
