### PR TITLE
ejabberd, oneteam and erlang/xmpp renewal

### PR DESCRIPTION
**Pull request by f055**
Renewals for ejabberd server, OneTeam clients and Erlang/XMPP lib. New ProcessOne logo and improved description on the sponsor page.

### CODE REVIEW

**Comment by f055** [comment]
Can we merge this?

**Comment by f055** [comment]
Hi @horazont - can you help merge this? It is way past due date now and've been sitting here since January.

**Comment by horazont** [comment]
@f055 Next time, please keep the renewals separated from other content changes. That makes it easier to judge the PR. I somehow missed it altogether, possibly because of that mix.

**Comment by f055** [comment]
@horazont Thanks for quick reaction, I'll keep that in mind.

**Pull request merged**
