### PR TITLE
Add IEEE paper to publications

### PR DESCRIPTION
**Pull request by Echolon**

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
Thanks! I added this in e1f94291930a705812722178fa4cb814a10a6bca

**Comment by jcbrand** [comment]
There are also these (not sure whether we should be adding every research paper however):

https://ieeexplore.ieee.org/document/8320956
https://ieeexplore.ieee.org/document/8394998
https://ieeexplore.ieee.org/document/9153556

**Comment by Echolon** [comment]
@jcbrand yes great! I would say that we just update it and if it gets overwhelmingly too much we should consider a different solution. but linking for now is good and also to give people something to eat for the moment :-)

**Comment by wurstsalat3000** [comment]
I went forward and added [papers.json](https://github.com/xsf/xmpp.org/blob/master/data/papers.json) with a custom rendering.

**Comment by Echolon** [comment]
Really awesome 😍 @wurstsalat3000

**Pull request closed without merging**
