### PR TITLE
Trademark - Remove .html from Save_as:

### LINKED ISSUE #203: Various issues with the trademark pages
These two pages, as linked from the main Jabber trademark page, don’t exist currently: https://xmpp.org/about/xsf/jabber-trademark/guidelines and https://xmpp.org/about/xsf/jabber-trademark/dispute-resolutions
The first one should be https://xmpp.org/about/xsf/jabber-trademark/usage-guidelines instead, I haven’t found the second one.

https://xmpp.org/about/xsf/jabber-trademark/pending-applications links to http://tracker.xmpp.org/browse/TRADEMARKS (which redirects to https://xmpp.org/), it should instead maybe list the open issues on github tagged with a trademark tag for example.

https://xmpp.org/about/xsf/jabber-trademark/who-needs-a-license says “described elsewhere on this web site”, this should be replaced with a link.

The various “please contact us” links point to https://xmpp.org/contact but it might be useful to add an id on the trademark paragraph to link directly to it.

The first link on https://xmpp.org/about/xsf/jabber-trademark/whats-required points to https://xmpp.org/about/xsf/jabber-trademark/trademark-license-agreement/ (with a final slash), which doesn’t exist, this one should redirect to the same URL without the final slash, or maybe just the link should be fixed.

### PR DESCRIPTION
**Pull request by Echolon**
Is it done with this "simple" change?

@ge0rg

closes #203

### CODE REVIEW

**Comment by ge0rg** [comment]
I don't know enough about the pelican build to estimate that, and I don't have a local deployment around to test. Sorry, no idea.

**Comment by Echolon** [comment]
@Zash may you have a look at the commit? Is is correct?

**Review by Zash — CHANGES_REQUESTED** [review]
I don't think this is correct. The `.html` suffix should probably be there, as it is on every other page.

**Comment by Echolon** [comment]
@Zash you mean like this? I added .html to both. maybe that was the error?

**Comment by mwild1** [comment]
This is obsoleted by the switch to hugo. The linked issue remains open (I added a comment there).

**Pull request closed without merging**
